<a href="https://colab.research.google.com/github/cesr1971/MLPYTHON/blob/main/MLPYTHON_TRAB01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Trabalho de Machine learning e Python**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('train.csv', encoding='utf-8')
# Carregar o arquivo

In [4]:
df.info()
# Conhecer a estrutura do DF

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20758 non-null  int64
 1   Gender                          20758 non-null  object
 2   Age                             20758 non-null  float64
 3   Height                          20758 non-null  float64
 4   Weight                          20758 non-null  float64
 5   family_history_with_overweight  20758 non-null  object
 6   FAVC                            20758 non-null  object
 7   FCVC                            20758 non-null  float64
 8   NCP                             20758 non-null  float64
 9   CAEC                            20758 non-null  object
 10  SMOKE                           20758 non-null  object
 11  CH2O                            20758 non-null  float64
 12  SCC                             20758 non-null  object
 13  FAF                             20758 non-null  float64
 14  TUE                             20758 non-null  float64
 15  CALC                            20758 non-null  object
 16  MTRANS                          20758 non-null  object
 17  NObeyesdad                      20758 non-null  object
dtypes: float64(8), int64(1), object(9)
memory usage: 2.9+ MB

In [5]:
# Conhecer as Dimensões da base
print(f"\nTotal de vendas (linhas): {df.shape[0]}")
print(f"Total de atributos (colunas): {df.shape[1]}")

Total de vendas (linhas): 20758
Total de atributos (colunas): 18

**Vamos criar duas colunas como sugestão em Aula.**

In [6]:
# Criar a coluna IMC (considerando height em centímetros e weight em kg)
df["IMC"] = df["Weight"] / (df["Height"] / 100) ** 2

# Arredondar o IMC para duas casas decimais
df["IMC"] = df["IMC"].round(2)

In [7]:
display(df)

,id,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,IMC
0,0,Male,24.443011,1.699998,81.669950,yes,yes,2.000000,2.983297,Sometimes,no,2.763573,no,0.000000,0.976473,Sometimes,Public_Transportation,Overweight_Level_II,282595.65
1,1,Female,18.000000,1.560000,57.000000,yes,yes,2.000000,3.000000,Frequently,no,2.000000,no,1.000000,1.000000,no,Automobile,Normal_Weight,234220.91
2,2,Female,18.000000,1.711460,50.165754,yes,yes,1.880534,1.411685,Sometimes,no,1.910378,no,0.866045,1.673584,no,Public_Transportation,Insufficient_Weight,171267.06
3,3,Female,20.952737,1.710730,131.274851,yes,yes,3.000000,3.000000,Sometimes,no,1.674061,no,1.467863,0.780199,Sometimes,Public_Transportation,Obesity_Type_III,448557.98
4,4,Male,31.641081,1.914186,93.798055,yes,yes,2.679664,1.971472,Sometimes,no,1.979848,no,1.967973,0.931721,Sometimes,Public_Transportation,Overweight_Level_II,255991.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20753,20753,Male,25.137087,1.766626,114.187096,yes,yes,2.919584,3.000000,Sometimes,no,2.151809,no,1.330519,0.196680,Sometimes,Public_Transportation,Obesity_Type_II,365870.84
20754,20754,Male,18.000000,1.710000,50.000000,no,yes,3.000000,4.000000,Frequently,no,1.000000,no,2.000000,1.000000,Sometimes,Public_Transportation,Insufficient_Weight,170992.78
20755,20755,Male,20.101026,1.819557,105.580491,yes,yes,2.407817,3.000000,Sometimes,no,2.000000,no,1.158040,1.198439,no,Public_Transportation,Obesity_Type_II,318898.41
20756,20756,Male,33.852953,1.700000,83.520113,yes,yes,2.671238,1.971472,Sometimes,no,2.144838,no,0.000000,0.973834,no,Automobile,Overweight_Level_II,288996.93
20757,20757,Male,26.680376,1.816547,118.134898,yes,yes,3.000000,3.000000,Sometimes,no,2.003563,no,0.684487,0.713823,Sometimes,Public_Transportation,Obesity_Type_II,358001.57

In [8]:
df.describe()
# Estatísticas gerais das colunas numéricas

,id,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE,IMC
count,20758.00000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000,20758.000000
mean,10378.50000,23.841804,1.700245,87.887768,2.445908,2.761332,2.029418,0.981747,0.616756,302418.416886
std,5992.46278,5.688072,0.087312,26.379443,0.533218,0.705375,0.608467,0.838302,0.602113,83339.319050
min,0.00000,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000,128685.410000
25%,5189.25000,20.000000,1.631856,66.000000,2.000000,3.000000,1.792022,0.008013,0.000000,240882.230000
50%,10378.50000,22.815416,1.700000,84.064875,2.393837,3.000000,2.000000,1.000000,0.573887,293847.570000
75%,15567.75000,26.000000,1.762887,111.600553,3.000000,3.000000,2.549617,1.587406,1.000000,370111.677500
max,20757.00000,61.000000,1.975663,165.057269,3.000000,4.000000,3.000000,3.000000,2.000000,549979.910000

In [11]:
df['CALC'].unique() # Indica Realiza consumo de alcool Frequentemente na base (Valor distinto).

array(['Sometimes', 'no', 'Frequently'], dtype=object)

In [12]:
df['MTRANS'].unique() # Indica Modo de Transporte (Valor Distinto).

array(['Public_Transportation', 'Automobile', 'Walking', 'Motorbike',
       'Bike'], dtype=object)

In [13]:
df['NObeyesdad'].unique() # Indica Nivel de Obesidade (Valor Distinto).

array(['Overweight_Level_II', 'Normal_Weight', 'Insufficient_Weight',
       'Obesity_Type_III', 'Obesity_Type_II', 'Overweight_Level_I',
       'Obesity_Type_I'], dtype=object)

In [14]:
df['SMOKE'].unique() # Indica se a pessoa é fumante (Valor Distinto).

array(['no', 'yes'], dtype=object)

In [15]:
df['CAEC'].unique() # Indica frequencia de alimentos entre as refeições (Valor Distinto).

array(['Sometimes', 'Frequently', 'no', 'Always'], dtype=object)

In [16]:
df['FAVC'].unique() # Indica se faz consumo de comida calorica (Valor Distinto).

array(['yes', 'no'], dtype=object)

In [17]:
df['family_history_with_overweight'].unique() # Indica se possui historico de Obesidade na Familia (Valor Distinto).

array(['yes', 'no'], dtype=object)